services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: subvenia_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - subvenia_net
    # AÑADIMOS ESTO: Le dice a Docker cómo saber si ES ya arrancó
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 12

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: subvenia_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${KIBANA_SERVICE_TOKEN}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - subvenia_net
    # MODIFICAMOS ESTO: Ahora Kibana esperará pacientemente la prueba de salud
    # depends_on:
    #   elasticsearch:
    #     condition: service_healthy

volumes:
  # Volumen persistente
  es_data:
    driver: local

networks:
  subvenia_net:
    driver: bridge